const FALLBACK_PRODUCTS = [
  'BTC-USD','ETH-USD','SOL-USD','XRP-USD','DOGE-USD','ADA-USD','AVAX-USD','LINK-USD','LTC-USD','BCH-USD',
  'DOT-USD','UNI-USD','AAVE-USD','ATOM-USD','NEAR-USD','ICP-USD','FIL-USD','APT-USD','ARB-USD','OP-USD',
  'SUI-USD','SEI-USD','INJ-USD','MKR-USD','COMP-USD','ETC-USD','ALGO-USD','GRT-USD','CRV-USD','BONK-USD'
];
const QUICK_PRODUCTS = ['BTC-USD','ETH-USD','SOL-USD','XRP-USD','DOGE-USD','LINK-USD'];
const USD_MINT = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
const SOL_MINT = 'So11111111111111111111111111111111111111112';
const DEMO = new URLSearchParams(location.search).get('demo') === '1';
const STORE_KEY = 'bravia-v3-state';
const BACKEND_KEY = 'bravia-backend-url';

const MODES = {
  AUTO:     { threshold:.555, cooldown:5000,  minHold:4000, maxHold:90000,  tp:.0065, sl:.0040, size:.18, maxPositions:4 },
  ULTRA:    { threshold:.505, cooldown:600,   minHold:800,  maxHold:10000,  tp:.0048, sl:.0028, size:.10, maxPositions:8 },
  FAST:     { threshold:.515, cooldown:1000,  minHold:1200, maxHold:18000,  tp:.0060, sl:.0035, size:.12, maxPositions:7 },
  BALANCED: { threshold:.600, cooldown:12000, minHold:9000, maxHold:180000, tp:.0100, sl:.0060, size:.22, maxPositions:4 },
  TREND:    { threshold:.660, cooldown:35000, minHold:30000,maxHold:600000, tp:.0220, sl:.0100, size:.28, maxPositions:3 },
  CUSTOM:   { threshold:.570, cooldown:7000,  minHold:5000, maxHold:120000, tp:.0080, sl:.0050, size:.20, maxPositions:4 },
};

const SNIPER_PRESETS = {
  SAFE: { label:'🛡 SAFE', minLiquidity:25000, minTx5m:35, minBuyRatio:.56, maxAgeMin:45, minVolume5m:9000, maxMcapLiq:35, minScore:78, tp:.18, sl:.08, maxHold:600000 },
  BALANCED: { label:'⚖ BALANCED', minLiquidity:10000, minTx5m:20, minBuyRatio:.53, maxAgeMin:60, minVolume5m:3500, maxMcapLiq:60, minScore:68, tp:.22, sl:.10, maxHold:420000 },
  FAST: { label:'⚡ FAST', minLiquidity:5000, minTx5m:10, minBuyRatio:.50, maxAgeMin:90, minVolume5m:1200, maxMcapLiq:100, minScore:58, tp:.25, sl:.12, maxHold:300000 },
  EXPERIMENTAL: { label:'☢ EXPERIMENTAL', minLiquidity:1500, minTx5m:5, minBuyRatio:.47, maxAgeMin:180, minVolume5m:400, maxMcapLiq:160, minScore:48, tp:.30, sl:.16, maxHold:180000 },
};

const ARENA_BLUEPRINTS = [
  ['Auto Adaptive','NORMAL','AUTO'],['Ultra Scalp','NORMAL','ULTRA'],['Fast Density','NORMAL','FAST'],['Balanced','NORMAL','BALANCED'],
  ['Trend Rider','NORMAL','TREND'],['Meme Normal','MEME','BALANCED'],['Sniper Safe','SNIPER','SAFE'],['Sniper Fast','SNIPER','FAST']
];

const state = {
  running:false, connected:false, selectedPair:'BTC-USD', chartRange:300, mode:'AUTO', products:[...FALLBACK_PRODUCTS],
  tickers:{}, history:{}, scores:{}, cash:10, startingCash:10, realizedPnl:0, frictionCost:0, positions:{}, trades:[], lastAction:{},
  peakEquity:10, maxDrawdown:0, logs:[], feeRate:.0015, slippageRate:.0003, scannerQuery:'', marketQuery:'',
  memePairs:[], memeByAddress:{}, memePositions:{}, memeSeen:new Set(), memeRefreshAt:0, sniperPreset:'BALANCED', sniperArmed:false,
  sniperStats:{detected:0,passed:0,entries:0,rejected:0}, sniperEvents:[], backend:localStorage.getItem(BACKEND_KEY)||'', backendOk:false,
  arenaRunning:false, arena:[], executionMode:'paper', walletAddress:'', firstTickAt:0, lastPersist:0,
};

const $ = id => document.getElementById(id);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const fmtMoney=(n,d=2)=>`$${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d})}`;
const fmtCompact=n=>{n=Number(n||0);if(Math.abs(n)>=1e9)return`${(n/1e9).toFixed(1)}B`;if(Math.abs(n)>=1e6)return`${(n/1e6).toFixed(1)}M`;if(Math.abs(n)>=1e3)return`${(n/1e3).toFixed(1)}K`;return n.toFixed(n<10?2:0)};
const fmtPct=n=>`${n>=0?'+':''}${Number(n||0).toFixed(2)}%`;
const nowTime=()=>new Date().toLocaleTimeString([], {hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'});
const safeNum=v=>Number.isFinite(Number(v))?Number(v):0;
const shortCA=ca=>ca?`${ca.slice(0,5)}…${ca.slice(-4)}`:'—';
const ageText=ms=>{const m=Math.max(0,Math.round(ms/60000));if(m<60)return`${m}m`;const h=Math.round(m/60);if(h<48)return`${h}h`;return`${Math.round(h/24)}d`};

function log(type,message){state.logs.unshift({time:nowTime(),type,message});state.logs=state.logs.slice(0,220);renderLog();}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function getHistory(pair){if(!state.history[pair])state.history[pair]=[];return state.history[pair]}
function getScore(pair){if(!state.scores[pair])state.scores[pair]={score:.5,signal:'WAIT',detail:'warming'};return state.scores[pair]}
function currentConfig(pair=state.selectedPair){if(state.mode!=='AUTO')return MODES[state.mode];const h=getHistory(pair);const v=volatility(h.slice(-45));if(v>.0022)return{...MODES.FAST,threshold:.54};if(v<.00035&&h.length>25)return{...MODES.TREND,threshold:.63};return MODES.AUTO}
function volatility(points){if(points.length<4)return 0;const rs=[];for(let i=1;i<points.length;i++)rs.push((points[i].price-points[i-1].price)/points[i-1].price);const mean=rs.reduce((a,b)=>a+b,0)/rs.length;return Math.sqrt(rs.reduce((a,b)=>a+(b-mean)**2,0)/rs.length)}
function momentum(h,n){if(h.length<n+1)return 0;return(h.at(-1).price-h.at(-1-n).price)/h.at(-1-n).price}

function calculateSignal(pair, cfg=currentConfig(pair)){
  const t=state.tickers[pair],h=getHistory(pair);if(!t||h.length<6)return{score:.5,signal:'WAIT',detail:`warming ${h.length}/6`};
  const m2=momentum(h,Math.min(2,h.length-1)),m5=momentum(h,Math.min(5,h.length-1)),m12=momentum(h,Math.min(12,h.length-1));
  const accel=m2-(m5-m2);const day=(t.change24h||0)/100;const spread=t.ask&&t.bid&&t.price?(t.ask-t.bid)/t.price:.001;const vol=volatility(h.slice(-35));
  let raw=0;raw+=clamp(m2/.0008,-1,1)*.24;raw+=clamp(m5/.0018,-1,1)*.25;raw+=clamp(m12/.0035,-1,1)*.19;raw+=clamp(accel/.0009,-1,1)*.13;raw+=clamp(day/.07,-1,1)*.10;raw-=clamp(spread/.003,0,1)*.05;raw-=clamp(vol/.006,0,1)*.04;
  const score=clamp(.5+raw/2,0,1);let signal='WAIT';if(score>=cfg.threshold)signal='BUY';else if(score<=1-cfg.threshold)signal='SELL';
  return{score,signal,detail:`m2 ${fmtPct(m2*100)} · vol ${(vol*100).toFixed(2)}% · spread ${(spread*100).toFixed(3)}%`};
}

function normalPositionValue(p){return p.qty*(state.tickers[p.pair]?.price||p.entry)}
function memePositionValue(p){const pair=state.memeByAddress[p.address];return p.qty*safeNum(pair?.priceUsd||p.entry)}
function equity(){return state.cash+Object.values(state.positions).reduce((s,p)=>s+normalPositionValue(p),0)+Object.values(state.memePositions).reduce((s,p)=>s+memePositionValue(p),0)}
function openPositionCount(){return Object.keys(state.positions).length+Object.keys(state.memePositions).length}
function canSpend(amount=.25){return state.cash>=amount}
function updateRiskStats(){const eq=equity();state.peakEquity=Math.max(state.peakEquity,eq);state.maxDrawdown=Math.max(state.maxDrawdown,state.peakEquity?((state.peakEquity-eq)/state.peakEquity)*100:0)}

function buyNormal(pair,reason,cfg=currentConfig(pair)){
  const t=state.tickers[pair];if(!t?.price||state.positions[pair]||openPositionCount()>=cfg.maxPositions||!canSpend())return false;
  const base=t.ask||t.price,fill=base*(1+state.slippageRate),budget=Math.max(.25,Math.min(state.cash*.22,state.cash*cfg.size)),notional=budget/(1+state.feeRate),fee=notional*state.feeRate,qty=notional/fill;
  if(notional<.20)return false;state.cash-=notional+fee;state.frictionCost+=fee+notional*state.slippageRate;state.positions[pair]={type:'NORMAL',pair,qty,entry:fill,cost:notional,buyFee:fee,openedAt:Date.now(),high:fill,reason};state.lastAction[pair]=Date.now();log('BUY',`${pair} ${fmtMoney(notional)} @ ${fmtMoney(fill,fill<100?4:2)} · ${reason}`);return true;
}
function sellNormal(pair,reason){const p=state.positions[pair],t=state.tickers[pair];if(!p||!t?.price)return false;const fill=(t.bid||t.price)*(1-state.slippageRate),gross=p.qty*fill,fee=gross*state.feeRate,proceeds=gross-fee,pnl=proceeds-p.cost-p.buyFee,pnlPct=pnl/(p.cost+p.buyFee)*100;state.cash+=proceeds;state.frictionCost+=fee+gross*state.slippageRate;state.realizedPnl+=pnl;state.trades.unshift({type:'NORMAL',pair,pnl,pnlPct,entry:p.entry,exit:fill,duration:Date.now()-p.openedAt,reason,at:Date.now()});delete state.positions[pair];state.lastAction[pair]=Date.now();log('SELL',`${pair} ${pnl>=0?'+':''}${fmtMoney(pnl,4)} (${fmtPct(pnlPct)}) · ${reason}`);return true}

function evaluateNormalBot(){if(!state.running||!state.connected)return;const candidates=[];for(const pair of state.products){const t=state.tickers[pair];if(!t)continue;const cfg=currentConfig(pair);const s=calculateSignal(pair,cfg);state.scores[pair]=s;const p=state.positions[pair];if(p){p.high=Math.max(p.high,t.price);const move=(t.price-p.entry)/p.entry,fromHigh=(t.price-p.high)/p.high,age=Date.now()-p.openedAt;if(move>=cfg.tp&&age>=cfg.minHold)sellNormal(pair,'take profit');else if(move<=-cfg.sl)sellNormal(pair,'stop loss');else if(move>cfg.tp*.45&&fromHigh<=-cfg.sl*.42&&age>=cfg.minHold)sellNormal(pair,'trailing exit');else if(age>=cfg.maxHold)sellNormal(pair,'max hold');else if(s.signal==='SELL'&&age>=cfg.minHold)sellNormal(pair,'signal reversal')}else if(s.signal==='BUY'&&Date.now()-(state.lastAction[pair]||0)>=cfg.cooldown)candidates.push({pair,s,cfg})}
  candidates.sort((a,b)=>b.s.score-a.s.score);const slots=Math.max(0,currentConfig().maxPositions-openPositionCount());for(const c of candidates.slice(0,slots)){if(!canSpend())break;buyNormal(c.pair,`score ${(c.s.score*100).toFixed(0)}`,c.cfg)}updateRiskStats();
}

async function discoverProducts(){if(DEMO)return;try{const r=await fetch('https://api.coinbase.com/api/v3/brokerage/market/products?limit=100&product_type=SPOT',{cache:'no-store'});if(!r.ok)throw Error(r.status);const j=await r.json();const products=(j.products||[]).filter(p=>p.quote_currency_id==='USD'&&!p.is_disabled&&p.status!=='offline').sort((a,b)=>safeNum(b.volume_24h)*safeNum(b.price)-safeNum(a.volume_24h)*safeNum(a.price)).map(p=>p.product_id);const preferred=[...FALLBACK_PRODUCTS,...products];state.products=[...new Set(preferred)].filter(x=>x.endsWith('-USD')).slice(0,80);$('marketUniverseCount').textContent=`${state.products.length} ASSETS`;log('MARKET',`Discovered ${state.products.length} Coinbase USD spot markets`)}catch(e){state.products=[...FALLBACK_PRODUCTS];$('marketUniverseCount').textContent=`${state.products.length} ASSETS`;log('RISK','Coinbase product discovery unavailable — using 30-pair fallback universe')}}

function connectMarket(){if(DEMO){seedDemo();return}let ws,reconnectTimer;const open=()=>{clearTimeout(reconnectTimer);setFeed(false,'CONNECTING');ws=new WebSocket('wss://advanced-trade-ws.coinbase.com');ws.onopen=()=>{for(let i=0;i<state.products.length;i+=20)ws.send(JSON.stringify({type:'subscribe',product_ids:state.products.slice(i,i+20),channel:'ticker'}));ws.send(JSON.stringify({type:'subscribe',channel:'heartbeats'}));setFeed(true,'LIVE COINBASE');log('MARKET',`Coinbase WebSocket live · scanning ${state.products.length} products`)};ws.onmessage=({data})=>{let msg;try{msg=JSON.parse(data)}catch{return}if(msg.channel!=='ticker')return;for(const ev of msg.events||[])for(const x of ev.tickers||[]){if(!state.products.includes(x.product_id))continue;const price=safeNum(x.price);if(!price)continue;const pair=x.product_id;state.tickers[pair]={pair,price,bid:safeNum(x.best_bid)||price,ask:safeNum(x.best_ask)||price,change24h:safeNum(x.price_percent_chg_24_h),volume24h:safeNum(x.volume_24_h),at:Date.now()};const h=getHistory(pair);if(!h.length||Date.now()-h.at(-1).t>=650){h.push({t:Date.now(),price});if(h.length>1400)h.shift()}else h[h.length-1]={t:h.at(-1).t,price};state.scores[pair]=calculateSignal(pair);state.firstTickAt ||= Date.now()}scheduleRender()};ws.onerror=()=>setFeed(false,'FEED ERROR');ws.onclose=()=>{setFeed(false,'RECONNECTING');log('ERROR','Market feed disconnected; automatic reconnect');reconnectTimer=setTimeout(open,1800)}};open()}
function setFeed(ok,label){state.connected=ok;$('feedStatus').textContent=label;$('feedDot').style.background=ok?'var(--green)':'var(--yellow)'}

async function refreshMemes(){if(DEMO){seedDemoMemes();return}try{const p=await fetch('https://api.dexscreener.com/token-profiles/latest/v1',{cache:'no-store'});if(!p.ok)throw Error(p.status);const rawProfiles=await p.json();const profiles=(Array.isArray(rawProfiles)?rawProfiles:[rawProfiles]).filter(x=>x&&x.chainId==='solana').slice(0,30);const addresses=[...new Set(profiles.map(x=>x.tokenAddress).filter(Boolean))].slice(0,30);if(!addresses.length)return;const d=await fetch(`https://api.dexscreener.com/tokens/v1/solana/${addresses.join(',')}`,{cache:'no-store'});if(!d.ok)throw Error(d.status);const pairs=await d.json();const best={};for(const pair of pairs||[]){const ca=pair.baseToken?.address;if(!ca)continue;if(!best[ca]||safeNum(pair.liquidity?.usd)>safeNum(best[ca].liquidity?.usd))best[ca]=pair}const profileMap=Object.fromEntries(profiles.map(x=>[x.tokenAddress,x]));state.memePairs=Object.values(best).map(x=>({...x,_profile:profileMap[x.baseToken?.address]||{},_risk:scoreMeme(x)})).sort((a,b)=>b._risk.score-a._risk.score);for(const pair of state.memePairs){const ca=pair.baseToken?.address;if(ca)state.memeByAddress[ca]=pair;handleNewMeme(pair)}state.memeRefreshAt=Date.now();renderMemes();renderMemePositions();log('MARKET',`Meme radar refreshed · ${state.memePairs.length} Solana tokens`)}catch(e){log('ERROR',`Meme radar refresh failed (${e.message})`);$('memeSourceBadge').textContent='RETRYING'}}

function scoreMeme(pair,security=null){const liq=safeNum(pair.liquidity?.usd),mcap=safeNum(pair.marketCap||pair.fdv),vol5=safeNum(pair.volume?.m5),buys=safeNum(pair.txns?.m5?.buys),sells=safeNum(pair.txns?.m5?.sells),tx=buys+sells,buyRatio=tx?buys/tx:.5,age=pair.pairCreatedAt?Date.now()-pair.pairCreatedAt:Infinity,ageMin=age/60000,ratio=liq?mcap/liq:999;let score=50;score+=clamp((Math.log10(Math.max(liq,100))-3)*13,-12,28);score+=clamp((buyRatio-.5)*70,-16,16);score+=clamp(Math.log10(Math.max(vol5,1)/1000)*7,-10,14);score-=clamp((ratio-30)/4,0,18);if(ageMin<10)score+=5;if(ageMin>1440)score-=4;if(tx<5)score-=9;if(security?.is_honeypot)score-=45;if(security?.freeze_authority)score-=15;if(security?.mint_authority)score-=10;score=clamp(Math.round(score),0,100);const risk=100-score;return{score,risk,liq,mcap,vol5,buys,sells,tx,buyRatio,ageMin,ratio}}
function passesPreset(pair,preset=SNIPER_PRESETS[state.sniperPreset]){const r=pair._risk||scoreMeme(pair);const reasons=[];if(r.liq<preset.minLiquidity)reasons.push('low liquidity');if(r.tx<preset.minTx5m)reasons.push('low 5m activity');if(r.buyRatio<preset.minBuyRatio)reasons.push('weak buy flow');if(r.ageMin>preset.maxAgeMin)reasons.push('too old');if(r.vol5<preset.minVolume5m)reasons.push('low volume');if(r.ratio>preset.maxMcapLiq)reasons.push('thin liquidity vs mcap');if(r.score<preset.minScore)reasons.push('score below preset');return{pass:reasons.length===0,reasons,r}}
function handleNewMeme(pair){const ca=pair.baseToken?.address;if(!ca||state.memeSeen.has(ca))return;state.memeSeen.add(ca);state.sniperStats.detected++;const chk=passesPreset(pair);if(chk.pass)state.sniperStats.passed++;else state.sniperStats.rejected++;state.sniperEvents.unshift({at:Date.now(),pair,pass:chk.pass,reasons:chk.reasons});state.sniperEvents=state.sniperEvents.slice(0,80);if(state.sniperArmed&&chk.pass)paperBuyMeme(pair,`sniper ${state.sniperPreset}`);renderSniper()}

function paperBuyMeme(pair,reason){const ca=pair.baseToken?.address,price=safeNum(pair.priceUsd);if(!ca||!price||state.memePositions[ca]||!canSpend(.25)||openPositionCount()>=6)return false;const budget=Math.max(.25,Math.min(state.cash*.16,1.25)),slip=Math.max(state.slippageRate,.003),fill=price*(1+slip),notional=budget/(1+state.feeRate),fee=notional*state.feeRate,qty=notional/fill;state.cash-=notional+fee;state.frictionCost+=fee+notional*slip;state.memePositions[ca]={type:'MEME',address:ca,symbol:pair.baseToken?.symbol||'MEME',qty,entry:fill,cost:notional,buyFee:fee,openedAt:Date.now(),high:fill,reason};state.sniperStats.entries++;log('SNIPER',`PAPER BUY ${pair.baseToken?.symbol||shortCA(ca)} ${fmtMoney(notional)} · ${reason}`);return true}
function sellMeme(ca,reason){const p=state.memePositions[ca],pair=state.memeByAddress[ca],price=safeNum(pair?.priceUsd);if(!p||!price)return false;const slip=Math.max(state.slippageRate,.004),fill=price*(1-slip),gross=p.qty*fill,fee=gross*state.feeRate,proceeds=gross-fee,pnl=proceeds-p.cost-p.buyFee,pnlPct=pnl/(p.cost+p.buyFee)*100;state.cash+=proceeds;state.realizedPnl+=pnl;state.frictionCost+=fee+gross*slip;state.trades.unshift({type:'MEME',pair:p.symbol,pnl,pnlPct,entry:p.entry,exit:fill,duration:Date.now()-p.openedAt,reason,at:Date.now()});delete state.memePositions[ca];log('SELL',`MEME ${p.symbol} ${pnl>=0?'+':''}${fmtMoney(pnl,4)} (${fmtPct(pnlPct)}) · ${reason}`);return true}
function evaluateMemePositions(){for(const [ca,p] of Object.entries(state.memePositions)){const pair=state.memeByAddress[ca],price=safeNum(pair?.priceUsd);if(!price)continue;p.high=Math.max(p.high,price);const move=(price-p.entry)/p.entry,age=Date.now()-p.openedAt,fromHigh=(price-p.high)/p.high,preset=SNIPER_PRESETS[state.sniperPreset];if(move>=preset.tp)sellMeme(ca,'meme take profit');else if(move<=-preset.sl)sellMeme(ca,'meme stop loss');else if(move>.09&&fromHigh<=-.05)sellMeme(ca,'meme trailing exit');else if(age>=preset.maxHold)sellMeme(ca,'meme max hold')}}

async function connectBackendStream(){if(!state.backend)return;try{const r=await fetch(`${state.backend.replace(/\/$/,'')}/health`,{signal:AbortSignal.timeout(4500)});if(!r.ok)throw Error(r.status);state.backendOk=true;$('backendStatus').textContent='✅ Backend online. Secret API integrations can be used.';$('sniperLatency').textContent='REAL-TIME';$('memeSourceBadge').textContent='BIRDEYE + DEX';const es=new EventSource(`${state.backend.replace(/\/$/,'')}/api/sniper/stream`);es.onmessage=e=>{try{const token=JSON.parse(e.data);if(token?.pair){const pair={...token.pair,_risk:scoreMeme(token.pair)};state.memeByAddress[pair.baseToken?.address]=pair;state.memePairs=[pair,...state.memePairs.filter(x=>x.baseToken?.address!==pair.baseToken?.address)].slice(0,60);handleNewMeme(pair);renderMemes()}}catch{}};es.onerror=()=>{$('sniperLatency').textContent='FALLBACK POLL'};return true}catch(e){state.backendOk=false;$('backendStatus').textContent='❌ Backend not reachable. Public browser feeds still work.';$('sniperLatency').textContent='POLLING';return false}}

async function analyzeCA(ca){ca=(ca||'').trim();if(ca.length<30){toast('Paste a valid Solana CA');return}$('rugResult').innerHTML='<div class="empty">Analyzing market + security signals…</div>';let pairs=[],security=null,enhanced=null;try{const r=await fetch(`https://api.dexscreener.com/token-pairs/v1/solana/${encodeURIComponent(ca)}`,{cache:'no-store'});if(r.ok)pairs=await r.json()}catch{}
  if(state.backendOk){try{const r=await fetch(`${state.backend.replace(/\/$/,'')}/api/security/${encodeURIComponent(ca)}`,{signal:AbortSignal.timeout(8000)});if(r.ok)enhanced=await r.json()}catch{}}
  const pair=(pairs||[]).sort((a,b)=>safeNum(b.liquidity?.usd)-safeNum(a.liquidity?.usd))[0]||enhanced?.dex?.[0];if(!pair){$('rugResult').innerHTML='<div class="verdict bad">No active Solana DEX pair found for this CA. That alone is a major warning for tradability.</div>';return}security=enhanced?.security||null;const r=scoreMeme(pair,security);let risk=r.risk;const flags=[];const add=(name,value,ok)=>flags.push({name,value,ok});add('Liquidity',fmtMoney(r.liq,0),r.liq>=10000);add('5m transactions',String(r.tx),r.tx>=20);add('Buy ratio',`${(r.buyRatio*100).toFixed(0)}%`,r.buyRatio>=.52);add('Pair age',ageText(Date.now()-(pair.pairCreatedAt||Date.now())),r.ageMin<1440);add('MCap / liquidity',r.ratio.toFixed(1),r.ratio<60);add('5m volume',fmtMoney(r.vol5,0),r.vol5>=3000);
  if(enhanced?.birdeye){const b=enhanced.birdeye;const top10=safeNum(b.top10_holder_percent||b.top10HolderPercent);if(top10){add('Top-10 holders',`${top10.toFixed(1)}%`,top10<35);risk+=top10>50?18:top10>35?8:-4}if(b.dev_percent!=null){add('Developer holding',`${safeNum(b.dev_percent).toFixed(1)}%`,safeNum(b.dev_percent)<5);risk+=safeNum(b.dev_percent)>10?16:0}}
  if(security){const freeze=Boolean(security.freeze_authority||security.freezeAuthority);const mint=Boolean(security.mint_authority||security.mintAuthority);const honey=Boolean(security.is_honeypot||security.isHoneypot);add('Freeze authority',freeze?'ACTIVE':'None',!freeze);add('Mint authority',mint?'ACTIVE':'None',!mint);add('Honeypot flag',honey?'FLAGGED':'No flag',!honey);if(freeze)risk+=18;if(mint)risk+=12;if(honey)risk+=45}
  risk=clamp(Math.round(risk),0,100);const verdict=risk<=28?'PRELIMINARY PASS — I would keep it on the candidate list, not blindly buy it.':risk<=55?'CAUTION — mixed signals; I would wait for stronger confirmation.':'HIGH RISK — I would not buy it from the available signals.';const cls=risk<=28?'good':risk>55?'bad':'';
  $('rugResult').innerHTML=`<div class="rug-score-grid"><div class="risk-score"><div><b class="${risk>55?'negative':risk<=28?'positive':''}">${risk}</b><span>RISK / 100</span><span>${pair.baseToken?.symbol||shortCA(ca)}</span></div></div><div><div class="risk-flags">${flags.map(f=>`<div class="risk-flag"><span>${f.name}</span><b class="${f.ok?'positive':'negative'}">${f.value}</b></div>`).join('')}</div><div class="verdict ${cls}">${verdict}<br><small>${state.backendOk?'Enhanced backend security sources included.':'Public mode only — connect backend for holder/security enrichment.'}</small></div></div></div>`;
}

function initArena(){if(state.arena.length)return;state.arena=ARENA_BLUEPRINTS.map(([name,type,mode],i)=>({id:i,name,type,mode,cash:10,start:10,positions:{},trades:[],peak:10,maxDD:0,lastAction:{}}))}
function arenaEquity(a){let v=a.cash;for(const p of Object.values(a.positions)){if(p.type==='NORMAL')v+=p.qty*(state.tickers[p.key]?.price||p.entry);else v+=p.qty*safeNum(state.memeByAddress[p.key]?.priceUsd||p.entry)}return v}
function arenaClose(a,key,price,friction,reason){const p=a.positions[key];if(!p)return;const fill=price*(1-friction),gross=p.qty*fill,fee=gross*state.feeRate,proceeds=gross-fee,pnl=proceeds-p.cost-p.buyFee;a.cash+=proceeds;a.trades.push({pnl,reason});delete a.positions[key];a.lastAction[key]=Date.now()}
function arenaOpen(a,key,type,price,cfg){if(a.positions[key]||a.cash<.25||Object.keys(a.positions).length>=3)return;const friction=type==='MEME'?.004:state.slippageRate,fill=price*(1+friction),budget=Math.max(.25,Math.min(a.cash*.24,1.5)),notional=budget/(1+state.feeRate),fee=notional*state.feeRate;a.cash-=notional+fee;a.positions[key]={key,type,qty:notional/fill,entry:fill,cost:notional,buyFee:fee,openedAt:Date.now(),high:fill,cfg};a.lastAction[key]=Date.now()}
function arenaTick(){if(!state.arenaRunning)return;initArena();for(const a of state.arena){if(a.type==='NORMAL'){const cfg=MODES[a.mode],best=state.products.map(pair=>({pair,s:calculateSignal(pair,cfg),t:state.tickers[pair]})).filter(x=>x.t).sort((x,y)=>y.s.score-x.s.score)[0];for(const [key,p] of Object.entries(a.positions)){const price=state.tickers[key]?.price;if(!price)continue;p.high=Math.max(p.high,price);const move=(price-p.entry)/p.entry,age=Date.now()-p.openedAt;if(move>=cfg.tp||move<=-cfg.sl||age>=cfg.maxHold||calculateSignal(key,cfg).signal==='SELL'&&age>=cfg.minHold)arenaClose(a,key,price,state.slippageRate,'normal exit')}if(best&&best.s.signal==='BUY'&&Date.now()-(a.lastAction[best.pair]||0)>=cfg.cooldown)arenaOpen(a,best.pair,'NORMAL',best.t.price,cfg)}else{const pair=state.memePairs[0];if(pair){const ca=pair.baseToken?.address,price=safeNum(pair.priceUsd);for(const [key,p] of Object.entries(a.positions)){const px=safeNum(state.memeByAddress[key]?.priceUsd);if(!px)continue;p.high=Math.max(p.high,px);const move=(px-p.entry)/p.entry,age=Date.now()-p.openedAt,pp=SNIPER_PRESETS[a.mode]||SNIPER_PRESETS.BALANCED;if(move>=pp.tp||move<=-pp.sl||age>=pp.maxHold)arenaClose(a,key,px,.004,'meme exit')}if(ca&&price){const ok=a.type==='SNIPER'?passesPreset(pair,SNIPER_PRESETS[a.mode]).pass:(pair._risk?.score||0)>=65;if(ok&&Date.now()-(a.lastAction[ca]||0)>5000)arenaOpen(a,ca,'MEME',price,SNIPER_PRESETS[a.mode]||SNIPER_PRESETS.BALANCED)}}}const eq=arenaEquity(a);a.peak=Math.max(a.peak,eq);a.maxDD=Math.max(a.maxDD,a.peak?((a.peak-eq)/a.peak)*100:0)}renderArena()}

function renderAll(){renderWallet();renderChart();renderScanner();renderPositions();renderMode();renderStats();renderMarketTable();renderSniper();renderArena();if(Date.now()-state.lastPersist>5000){persist();state.lastPersist=Date.now()}}
function renderWallet(){const eq=equity(),pnl=eq-state.startingCash;$('equity').textContent=fmtMoney(eq);$('cash').textContent=fmtMoney(state.cash);$('exposure').textContent=fmtMoney(eq-state.cash);$('tradeCount').textContent=state.trades.length;$('openCount').textContent=openPositionCount();$('pnl').textContent=`${pnl>=0?'+':''}${fmtMoney(pnl)} · ${fmtPct(state.startingCash?pnl/state.startingCash*100:0)}`;$('pnl').className=`pnl ${pnl<0?'negative':'positive'}`;$('positionsValue').textContent=fmtMoney(eq-state.cash)}
function renderMode(){const cfg=currentConfig();$('cfgThreshold').textContent=`${Math.round(cfg.threshold*100)}%`;$('cfgCooldown').textContent=`${(cfg.cooldown/1000).toFixed(1)}s`;$('cfgExit').textContent=`${(cfg.tp*100).toFixed(2)}% / ${(cfg.sl*100).toFixed(2)}%`;$('cfgSize').textContent=`${Math.round(cfg.size*100)}% cash`;$('cfgMaxPositions').textContent=cfg.maxPositions;$('modePulse').textContent=state.mode}
function renderQuickPairs(){$('quickPairs').innerHTML=QUICK_PRODUCTS.filter(p=>state.products.includes(p)).map(p=>`<button class="chip ${state.selectedPair===p?'active':''}" data-pair="${p}">${p.replace('-USD','')}</button>`).join('')}
function renderScanner(){const q=state.scannerQuery.toUpperCase();const rows=state.products.filter(p=>state.tickers[p]).map(pair=>({pair,t:state.tickers[pair],s:getScore(pair)})).filter(x=>!q||x.pair.includes(q)).sort((a,b)=>b.s.score-a.s.score).slice(0,16);$('assetCount').textContent=`${Object.keys(state.tickers).length} LIVE`;$('scanner').innerHTML=rows.length?rows.map(({pair,t,s})=>{const score=Math.round(s.score*100),spread=t.ask&&t.bid?(t.ask-t.bid)/t.price*100:0;return`<article class="panel asset-card" data-select="${pair}"><div class="asset-head"><div><div class="asset-symbol">${pair.replace('-USD','')}</div><div class="asset-sub">${pair} · SPOT</div></div><div><div class="asset-price">${fmtMoney(t.price,t.price<1?5:t.price<100?3:2)}</div><div class="asset-sub ${t.change24h<0?'negative':'positive'}">${fmtPct(t.change24h)} 24h</div></div></div><div class="score-row"><span class="signal ${s.signal}">${s.signal}</span><div class="score-bar"><div class="score-fill" style="width:${score}%"></div></div><b>${score}</b></div><div class="asset-meta"><div><span>Spread</span> ${spread.toFixed(3)}%</div><div><span>Vol 24h</span> ${fmtCompact(t.volume24h)}</div></div></article>`}).join(''):'<div class="empty">Waiting for market data…</div>';renderQuickPairs()}
function renderMarketTable(){const q=state.marketQuery.toUpperCase();const rows=state.products.filter(p=>!q||p.includes(q)).map(pair=>({pair,t:state.tickers[pair],s:getScore(pair)})).sort((a,b)=>(b.t?.volume24h||0)-(a.t?.volume24h||0));$('marketTable').innerHTML=rows.map(({pair,t,s})=>`<div class="market-row" data-select="${pair}"><div class="market-name"><i class="coin-dot"></i><b>${pair.replace('-USD','')}</b></div><b>${t?fmtMoney(t.price,t.price<1?5:t.price<100?3:2):'—'}</b><span class="${t?.change24h<0?'negative':'positive'}">${t?fmtPct(t.change24h):'—'}</span><span class="signal ${s.signal}">${s.signal}</span><span>${Math.round(s.score*100)}</span><span>${t?.ask&&t?.bid?(((t.ask-t.bid)/t.price)*100).toFixed(3)+'%':'—'}</span></div>`).join('')}

function renderChart(){const pair=state.selectedPair,t=state.tickers[pair],all=getHistory(pair),cut=Date.now()-state.chartRange*1000,h=all.filter(x=>x.t>=cut);$('chartPair').textContent=pair;$('chartPrice').textContent=t?fmtMoney(t.price,t.price<1?5:t.price<100?3:2):'—';$('chartChange').textContent=t?`${fmtPct(t.change24h)} 24h`:'—';$('chartChange').className=t?.change24h<0?'negative':'positive';$('chartMeta').textContent=h.length?`${h.length} ticks · ${state.chartRange/60}m window · live bid/ask`:'Waiting for live ticks…';const c=$('chart'),rect=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(300,rect.width),hh=Math.max(210,rect.height);if(c.width!==Math.round(w*dpr)||c.height!==Math.round(hh*dpr)){c.width=Math.round(w*dpr);c.height=Math.round(hh*dpr)}const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,hh);ctx.fillStyle='#05070d';ctx.fillRect(0,0,w,hh);ctx.strokeStyle='rgba(99,239,255,.075)';ctx.lineWidth=1;for(let i=0;i<=5;i++){const y=18+(hh-42)*i/5;ctx.beginPath();ctx.moveTo(44,y);ctx.lineTo(w-12,y);ctx.stroke()}for(let i=0;i<=5;i++){const x=44+(w-56)*i/5;ctx.beginPath();ctx.moveTo(x,12);ctx.lineTo(x,hh-24);ctx.stroke()}if(h.length<2){ctx.fillStyle='#59737d';ctx.font='10px monospace';ctx.fillText('COLLECTING LIVE PRICE DATA…',54,hh/2);return}const prices=h.map(x=>x.price),mn=Math.min(...prices),mx=Math.max(...prices),pad=Math.max((mx-mn)*.16,mx*.00025),lo=mn-pad,hi=mx+pad,xOf=i=>44+(w-58)*i/(h.length-1),yOf=p=>14+(hh-42)*(1-(p-lo)/(hi-lo));const grad=ctx.createLinearGradient(0,18,0,hh-26);grad.addColorStop(0,'rgba(255,36,200,.25)');grad.addColorStop(1,'rgba(99,239,255,0)');ctx.beginPath();h.forEach((p,i)=>{const x=xOf(i),y=yOf(p.price);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.lineTo(xOf(h.length-1),hh-25);ctx.lineTo(xOf(0),hh-25);ctx.closePath();ctx.fillStyle=grad;ctx.fill();ctx.beginPath();h.forEach((p,i)=>{const x=xOf(i),y=yOf(p.price);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#ff24c8';ctx.lineWidth=2;ctx.shadowColor='rgba(255,36,200,.55)';ctx.shadowBlur=7;ctx.stroke();ctx.shadowBlur=0;const last=h.at(-1),ly=yOf(last.price);ctx.setLineDash([4,4]);ctx.strokeStyle='rgba(86,255,154,.5)';ctx.beginPath();ctx.moveTo(44,ly);ctx.lineTo(w-12,ly);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#7f9ca8';ctx.font='9px monospace';for(let i=0;i<=4;i++){const p=hi-(hi-lo)*i/4;ctx.fillText(p<1?p.toFixed(5):p<100?p.toFixed(2):p.toFixed(0),3,20+(hh-42)*i/4)}ctx.fillStyle='#56ff9a';ctx.beginPath();ctx.arc(xOf(h.length-1),ly,3.5,0,Math.PI*2);ctx.fill()}

function renderPositions(){const normal=Object.values(state.positions).map(p=>{const px=state.tickers[p.pair]?.price||p.entry,pnl=(px-p.entry)*p.qty-p.buyFee;return{key:p.pair,label:p.pair.replace('-USD',''),type:'NORMAL',entry:p.entry,pnl}}),memes=Object.values(state.memePositions).map(p=>{const px=safeNum(state.memeByAddress[p.address]?.priceUsd||p.entry),pnl=(px-p.entry)*p.qty-p.buyFee;return{key:p.address,label:p.symbol,type:'MEME',entry:p.entry,pnl}}),rows=[...normal,...memes];$('positions').innerHTML=rows.length?rows.map(p=>`<div class="position-row"><div><b>${p.label}</b> <span class="position-type">${p.type}</span></div><span>Entry ${fmtMoney(p.entry,p.entry<1?6:2)}</span><b class="${p.pnl<0?'negative':'positive'}">${p.pnl>=0?'+':''}${fmtMoney(p.pnl,4)}</b><button class="text-btn" data-close="${p.key}" data-type="${p.type}">CLOSE</button></div>`).join(''):'<div class="empty">No open positions.</div>'}
function renderLog(){$('log').innerHTML=state.logs.length?state.logs.map(x=>`<div class="log-line"><time>${x.time}</time><span class="log-type ${x.type}">${x.type}</span><span>${escapeHtml(x.message)}</span></div>`).join(''):'<div class="empty">System ready. Start the paper bot when live market data arrives.</div>'}
function renderStats(){const wins=state.trades.filter(t=>t.pnl>0),best=[...state.trades].sort((a,b)=>b.pnl-a.pnl)[0],worst=[...state.trades].sort((a,b)=>a.pnl-b.pnl)[0];$('winRate').textContent=state.trades.length?`${(wins.length/state.trades.length*100).toFixed(1)}%`:'0%';$('realized').textContent=`${state.realizedPnl>=0?'+':''}${fmtMoney(state.realizedPnl,4)}`;$('realized').className=state.realizedPnl<0?'negative':'positive';$('fees').textContent=fmtMoney(state.frictionCost,4);$('drawdown').textContent=`${state.maxDrawdown.toFixed(2)}%`;$('bestTrade').textContent=best?`${best.pair} ${fmtPct(best.pnlPct)}`:'—';$('worstTrade').textContent=worst?`${worst.pair} ${fmtPct(worst.pnlPct)}`:'—'}

function renderMemes(){$('memeGrid').innerHTML=state.memePairs.length?state.memePairs.slice(0,30).map(pair=>{const r=pair._risk||scoreMeme(pair),ca=pair.baseToken?.address||'',img=pair.info?.imageUrl||pair._profile?.icon,name=pair.baseToken?.name||'Unknown',sym=pair.baseToken?.symbol||'MEME';return`<article class="panel meme-card"><div class="meme-top">${img?`<img class="token-img" src="${escapeAttr(img)}" alt="" onerror="this.outerHTML='<div class=&quot;token-img token-fallback&quot;>${escapeHtml(sym.slice(0,1))}</div>'">`:`<div class="token-img token-fallback">${escapeHtml(sym.slice(0,1))}</div>`}<div><div class="meme-name">${escapeHtml(name)}</div><div class="meme-symbol">${escapeHtml(sym)} · ${ageText(Date.now()-(pair.pairCreatedAt||Date.now()))} old</div></div></div><div class="meme-metrics"><div><span>LIQUIDITY</span><b>${fmtMoney(r.liq,0)}</b></div><div><span>VOL 5M</span><b>${fmtMoney(r.vol5,0)}</b></div><div><span>5M TX</span><b>${r.tx}</b></div><div><span>BUY FLOW</span><b>${(r.buyRatio*100).toFixed(0)}%</b></div><div><span>MCAP</span><b>$${fmtCompact(r.mcap)}</b></div><div><span>BRAVIA</span><b class="${r.score>=70?'positive':r.score<50?'negative':''}">${r.score}/100</b></div></div><div class="risk-meter"><i style="width:${r.score}%"></i></div><div class="meme-actions"><span class="ca-short">${shortCA(ca)}</span><button class="text-btn" data-rug-ca="${ca}">RISK CHECK →</button></div></article>`}).join(''):'<div class="panel empty" style="padding:18px">Loading fresh Solana token data…</div>'}
function renderSniper(){const preset=SNIPER_PRESETS[state.sniperPreset];$('sniperPresets').innerHTML=Object.entries(SNIPER_PRESETS).map(([k,p])=>`<button class="preset-btn ${k===state.sniperPreset?'active':''}" data-preset="${k}"><b>${p.label}</b><span>Score ≥ ${p.minScore} · liquidity ≥ ${fmtMoney(p.minLiquidity,0)}</span></button>`).join('');$('presetReadout').innerHTML=`Liquidity ≥ <b>${fmtMoney(preset.minLiquidity,0)}</b><br>5m transactions ≥ <b>${preset.minTx5m}</b><br>Buy ratio ≥ <b>${Math.round(preset.minBuyRatio*100)}%</b><br>5m volume ≥ <b>${fmtMoney(preset.minVolume5m,0)}</b><br>Pair age ≤ <b>${preset.maxAgeMin}m</b><br>BRAVIA score ≥ <b>${preset.minScore}</b>`;$('sniperDetected').textContent=state.sniperStats.detected;$('sniperPassed').textContent=state.sniperStats.passed;$('sniperEntries').textContent=state.sniperStats.entries;$('sniperRejected').textContent=state.sniperStats.rejected;$('sniperState').textContent=state.sniperArmed?'ARMED · PAPER':'DISARMED';$('armSniper').textContent=state.sniperArmed?'■ DISARM SNIPER':'⌖ ARM SNIPER';$('armSniper').className=state.sniperArmed?'btn primary':'btn danger-outline';$('sniperFeed').className=`sniper-feed ${state.sniperEvents.length?'':'empty'}`;$('sniperFeed').innerHTML=state.sniperEvents.length?state.sniperEvents.map(x=>`<div class="sniper-event"><span>${new Date(x.at).toLocaleTimeString([], {hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span><div><b>${escapeHtml(x.pair.baseToken?.symbol||'NEW')} · ${shortCA(x.pair.baseToken?.address)}</b><div class="asset-sub">${x.pass?'Preset passed':escapeHtml(x.reasons.slice(0,2).join(', '))}</div></div><b class="sniper-decision ${x.pass?'pass':'reject'}">${x.pass?'PASS':'REJECT'}</b></div>`).join(''):'Waiting for new Solana token events…'}
function renderArena(){initArena();const sorted=[...state.arena].sort((a,b)=>arenaEquity(b)-arenaEquity(a));$('arenaRows').innerHTML=sorted.map((a,i)=>{const eq=arenaEquity(a),pnl=(eq-a.start)/a.start*100,wins=a.trades.filter(t=>t.pnl>0).length,win=a.trades.length?wins/a.trades.length*100:0,score=Math.round(clamp(50+pnl*1.8-a.maxDD*2+Math.min(a.trades.length,20)*.5,0,100));return`<div class="leader-row"><b class="rank">${i+1}</b><div class="strategy-name"><b>${a.name}</b><span>${a.type} · ${a.mode}</span></div><b>${fmtMoney(eq)}</b><b class="${pnl<0?'negative':'positive'}">${fmtPct(pnl)}</b><span>${a.trades.length}</span><span>${win.toFixed(0)}%</span><span>${a.maxDD.toFixed(1)}%</span><b>${score}</b></div>`}).join('');$('arenaToggle').textContent=state.arenaRunning?'■ STOP ALL':'⚔ START ALL'}
function renderProviders(){const providers=[['Coinbase','Normal crypto ticker + public product universe',state.connected],['DEX Screener','Memecoin market/liquidity fallback',state.memePairs.length>0],['BRAVIA Backend','Secret-key proxy + SSE stream',state.backendOk],['Birdeye','Real-time new-token/new-pair stream',state.backendOk],['GoPlus','Solana token security enrichment',state.backendOk],['Helius','Solana RPC / wallet read data',state.backendOk],['Jupiter','Swap quotes / execution modelling',state.backendOk],['OpenAI','Paper-session supervisor / diagnostics',state.backendOk]];$('providerList').innerHTML=providers.map(([n,d,ok])=>`<div class="provider"><div><b>${n}</b><span>${d}</span></div><b class="provider-status ${ok?'positive':''}">${ok?'● READY':'○ OPTIONAL'}</b></div>`).join('')}

function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(s=''){return escapeHtml(s).replace(/`/g,'&#96;')}
function scheduleRender(){if(scheduleRender.pending)return;scheduleRender.pending=true;requestAnimationFrame(()=>{scheduleRender.pending=false;renderAll()})}
function persist(){try{localStorage.setItem(STORE_KEY,JSON.stringify({cash:state.cash,startingCash:state.startingCash,realizedPnl:state.realizedPnl,frictionCost:state.frictionCost,trades:state.trades.slice(0,250),peakEquity:state.peakEquity,maxDrawdown:state.maxDrawdown,mode:state.mode,feeRate:state.feeRate,slippageRate:state.slippageRate,arena:state.arena,sniperPreset:state.sniperPreset}))}catch{}}
function restore(){try{const s=JSON.parse(localStorage.getItem(STORE_KEY)||'{}');for(const k of ['cash','startingCash','realizedPnl','frictionCost','peakEquity','maxDrawdown','feeRate','slippageRate'])if(Number.isFinite(s[k]))state[k]=s[k];if(Array.isArray(s.trades))state.trades=s.trades;if(Array.isArray(s.arena))state.arena=s.arena;if(MODES[s.mode])state.mode=s.mode;if(SNIPER_PRESETS[s.sniperPreset])state.sniperPreset=s.sniperPreset}catch{}}

function seedDemo(){state.products=[...FALLBACK_PRODUCTS];const base={BTC:78161.53,ETH:3872.18,SOL:182.44,XRP:.628,DOGE:.218,ADA:.485,AVAX:34.1,LINK:18.9,LTC:92.4,BCH:489,DOT:6.1,UNI:11.4,AAVE:282,ATOM:8.3,NEAR:5.2,ICP:9.8,FIL:4.3,APT:8.6,ARB:.78,OP:1.82,SUI:3.7,SEI:.41,INJ:25.5,MKR:2300,COMP:56,ETC:24.4,ALGO:.19,GRT:.21,CRV:.39,BONK:.000027};const now=Date.now();for(const pair of state.products){const sym=pair.replace('-USD',''),p=base[sym]||Math.random()*20+1,chg=(Math.random()-.45)*9;state.tickers[pair]={pair,price:p,bid:p*.9998,ask:p*1.0002,change24h:chg,volume24h:Math.random()*1e8,at:now};const h=getHistory(pair);for(let i=240;i>=0;i--){const trend=(240-i)*chg/100/500,wiggle=Math.sin(i/8)*.003+(Math.random()-.5)*.0015;h.push({t:now-i*1000,price:p*(1-trend+wiggle)})}state.scores[pair]=calculateSignal(pair)}setFeed(true,'DEMO DATA');state.firstTickAt=Date.now();seedDemoMemes();renderAll()}
function seedDemoMemes(){const now=Date.now();state.memePairs=Array.from({length:9},(_,i)=>{const liq=5000+i*8500,buys=12+i*8,sells=5+i*3,p={chainId:'solana',dexId:'pumpfun',baseToken:{address:`DemoCA${i}xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx${i}`,name:['Neon Cat','Byte Pepe','MoonBot','Turbo Frog','Pink Whale','Sol Duck','Laser Dog','Orbit Coin','MemeGrid'][i],symbol:['NCAT','BPEPE','MOON','TFROG','PWHALE','SDUCK','LDOG','ORBIT','GRID'][i]},priceUsd:String(.00002*(i+1)),liquidity:{usd:liq},marketCap:liq*(18+i*3),pairCreatedAt:now-(i+1)*4*60000,volume:{m5:1500+i*1900,h1:22000},txns:{m5:{buys,sells}},priceChange:{m5:(i-2)*3.1},info:{}};p._risk=scoreMeme(p);state.memeByAddress[p.baseToken.address]=p;return p});for(const p of state.memePairs)handleNewMeme(p);renderMemes();renderSniper()}

function renderMemePositions(){renderPositions()}
function syncMemeAutoButton(){const b=$('memeAutoToggle');if(!b)return;b.textContent=state.memeAuto?'■ STOP MEME NORMAL':'▶ MEME NORMAL';b.className=state.memeAuto?'btn primary':'btn secondary'}
function evaluateMemeNormalBot(){if(!state.running||!state.memeAuto||!state.memePairs.length)return;state.memeLastAction||={};const candidates=state.memePairs.map(pair=>({pair,r:pair._risk||scoreMeme(pair)})).filter(x=>x.r.score>=66&&x.r.liq>=8000&&x.r.tx>=15&&x.r.buyRatio>=.51&&x.r.ageMin<=360).sort((a,b)=>b.r.score-a.r.score);for(const {pair,r} of candidates){const ca=pair.baseToken?.address;if(!ca||state.memePositions[ca]||Date.now()-(state.memeLastAction[ca]||0)<15000)continue;if(Object.keys(state.memePositions).length>=2||!canSpend(.25))break;if(paperBuyMeme(pair,`meme normal score ${r.score}`))state.memeLastAction[ca]=Date.now()}syncMemeAutoButton()}


function showView(view){
  const target=$(`view-${view}`);if(!target)return;
  document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x===target));
  document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));
  if(view==='memes')renderMemes();if(view==='sniper')renderSniper();if(view==='arena')renderArena();if(view==='setup')renderProviders();
  if(view==='overview')setTimeout(renderChart,30);
  try{window.scrollTo({top:0,behavior:'smooth'})}catch{window.scrollTo(0,0)}
}

function selectPairHandler(e){
  const el=e.target.closest('[data-select],[data-pair]');if(!el)return;
  const pair=el.dataset.select||el.dataset.pair;if(!pair||!state.products.includes(pair))return;
  state.selectedPair=pair;renderQuickPairs();renderChart();renderMode();
  if(!document.getElementById('view-overview').classList.contains('active'))showView('overview');
}

async function requestAIReview(){
  const out=$('aiReview');
  if(!state.backendOk){out.className='ai-review';out.textContent='Backend is not online. Add the BRAVIA backend URL in Setup and configure OPENAI_API_KEY on the server.';toast('AI review needs the backend');return}
  out.className='ai-review';out.textContent='Reviewing paper-session statistics…';
  const payload={mode:state.mode,equity:equity(),startingCash:state.startingCash,realizedPnl:state.realizedPnl,frictionCost:state.frictionCost,maxDrawdown:state.maxDrawdown,trades:state.trades.slice(0,100),arena:state.arena.map(a=>({name:a.name,type:a.type,mode:a.mode,equity:arenaEquity(a),start:a.start,trades:a.trades.length,wins:a.trades.filter(t=>t.pnl>0).length,maxDD:a.maxDD}))};
  try{const r=await fetch(`${state.backend.replace(/\/$/,'')}/api/ai/review`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(22000)});const j=await r.json();if(!r.ok)throw Error(j.error||r.status);out.innerHTML=escapeHtml(j.review||'No review returned.').replace(/\n/g,'<br>');toast('AI review complete')}catch(e){out.textContent=`AI review unavailable: ${e.message}`;toast('AI review failed')}
}

async function connectReadOnlyWallet(){
  const provider=window.phantom?.solana||window.solana;
  if(!provider?.connect){$('walletState').textContent='WALLET NOT FOUND';$('walletAddress').textContent='Open BRAVIA inside a compatible Solana wallet browser or install its extension.';toast('No Solana wallet provider found');return}
  try{const result=await provider.connect({onlyIfTrusted:false});const address=String(result?.publicKey||provider.publicKey||'');if(!address)throw Error('No public address returned');state.walletAddress=address;$('walletState').textContent='READ-ONLY CONNECTED';$('walletAddress').textContent=address;$('executionBadge').textContent='LIVE PREVIEW · LOCKED';toast('Public wallet connected — signing stays disabled');if(state.backendOk){try{const r=await fetch(`${state.backend.replace(/\/$/,'')}/api/wallet/${encodeURIComponent(address)}/balance`,{signal:AbortSignal.timeout(6000)});if(r.ok){const j=await r.json();$('walletAddress').textContent=`${address} · ${safeNum(j.sol).toFixed(4)} SOL (read-only)`}}catch{}}}catch(e){$('walletState').textContent='NOT CONNECTED';$('walletAddress').textContent=e.message||'Connection cancelled';toast('Wallet connection cancelled')}
}

function savePaperAssumptions(){
  const cash=Math.max(1,safeNum($('settingCash').value)||10),fee=clamp(safeNum($('settingFee').value)/100,0,.02),slip=clamp(safeNum($('settingSlippage').value)/100,0,.02);
  if(cash!==state.startingCash&&(state.trades.length||openPositionCount())){if(!confirm('Changing starting balance resets the current paper session. Continue?'))return;state.cash=cash;state.startingCash=cash;state.realizedPnl=0;state.frictionCost=0;state.positions={};state.memePositions={};state.trades=[];state.peakEquity=cash;state.maxDrawdown=0}
  else if(!state.trades.length&&!openPositionCount()){state.cash=cash;state.startingCash=cash;state.peakEquity=cash}
  state.feeRate=fee;state.slippageRate=slip;persist();renderAll();toast('Paper assumptions saved')
}

function resetArena(){state.arenaRunning=false;state.arena=[];initArena();renderArena();persist();toast('Strategy Arena reset')}

function bindUI(){
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
  $('openSetup').addEventListener('click',()=>showView('setup'));
  $('choosePaper').addEventListener('click',()=>{state.executionMode='paper';$('bootModal').classList.add('hidden');$('executionBadge').textContent='PAPER MODE';toast('Paper engine ready')});
  $('chooseLive').addEventListener('click',()=>{state.executionMode='live-preview';$('bootModal').classList.add('hidden');$('executionBadge').textContent='LIVE PREVIEW · LOCKED';showView('setup');toast('Live execution is locked; wallet connection is read-only')});
  $('startBtn').addEventListener('click',()=>{state.running=true;$('startBtn').disabled=true;$('stopBtn').disabled=false;log('SIGNAL',`Paper bot started · ${state.mode} · ${state.products.length} markets`);toast('Paper bot started')});
  $('stopBtn').addEventListener('click',()=>{state.running=false;$('startBtn').disabled=false;$('stopBtn').disabled=true;log('RISK','Paper bot stopped by user');toast('Bot stopped')});
  $('modeGrid').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(!b)return;state.mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===state.mode));renderMode();persist();log('SIGNAL',`Mode changed to ${state.mode}`)});
  $('clearLog').addEventListener('click',()=>{state.logs=[];renderLog()});
  $('scannerSearch').addEventListener('input',e=>{state.scannerQuery=e.target.value;renderScanner()});
  $('marketSearch').addEventListener('input',e=>{state.marketQuery=e.target.value;renderMarketTable()});
  $('scanner').addEventListener('click',selectPairHandler);$('marketTable').addEventListener('click',selectPairHandler);$('quickPairs').addEventListener('click',selectPairHandler);
  document.querySelector('.range-switch').addEventListener('click',e=>{const b=e.target.closest('[data-range]');if(!b)return;state.chartRange=Number(b.dataset.range);document.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('active',x===b));renderChart()});
  $('positions').addEventListener('click',e=>{const b=e.target.closest('[data-close]');if(!b)return;b.dataset.type==='MEME'?sellMeme(b.dataset.close,'manual close'):sellNormal(b.dataset.close,'manual close');renderAll()});
  $('refreshMemes').addEventListener('click',()=>refreshMemes());$('memeAutoToggle').addEventListener('click',()=>{state.memeAuto=!state.memeAuto;syncMemeAutoButton();log('SNIPER',state.memeAuto?'Meme Normal paper mode enabled':'Meme Normal paper mode disabled');toast(state.memeAuto?'Meme Normal enabled':'Meme Normal stopped')});
  $('memeGrid').addEventListener('click',e=>{const b=e.target.closest('[data-rug-ca]');if(!b)return;$('caInput').value=b.dataset.rugCa;showView('rugcheck');analyzeCA(b.dataset.rugCa)});
  $('sniperPresets').addEventListener('click',e=>{const b=e.target.closest('[data-preset]');if(!b)return;state.sniperPreset=b.dataset.preset;renderSniper();persist();toast(`${SNIPER_PRESETS[state.sniperPreset].label} preset selected`)});
  $('armSniper').addEventListener('click',()=>{state.sniperArmed=!state.sniperArmed;renderSniper();log('SNIPER',state.sniperArmed?`Paper sniper armed · ${state.sniperPreset}`:'Paper sniper disarmed');toast(state.sniperArmed?'Paper sniper armed':'Sniper disarmed')});
  $('analyzeCA').addEventListener('click',()=>analyzeCA($('caInput').value));$('caInput').addEventListener('keydown',e=>{if(e.key==='Enter')analyzeCA(e.currentTarget.value)});
  $('arenaToggle').addEventListener('click',()=>{state.arenaRunning=!state.arenaRunning;renderArena();persist();toast(state.arenaRunning?'All strategy wallets running':'Strategy Arena paused')});$('arenaReset').addEventListener('click',resetArena);
  $('aiReviewBtn').addEventListener('click',requestAIReview);
  $('saveBackend').addEventListener('click',async()=>{state.backend=$('backendUrl').value.trim().replace(/\/$/,'');if(state.backend)localStorage.setItem(BACKEND_KEY,state.backend);else localStorage.removeItem(BACKEND_KEY);$('backendStatus').textContent=state.backend?'Testing backend…':'Not configured. Public browser feeds remain available.';await connectBackendStream();renderProviders();toast(state.backendOk?'Backend connected':'Public feeds only')});
  $('savePaperSettings').addEventListener('click',savePaperAssumptions);$('connectWallet').addEventListener('click',connectReadOnlyWallet);
  window.addEventListener('resize',()=>{if(document.getElementById('view-overview').classList.contains('active'))renderChart()},{passive:true});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)renderAll()});
}

async function boot(){
  restore();initArena();if(typeof state.memeAuto!=='boolean')state.memeAuto=false;syncMemeAutoButton();
  $('backendUrl').value=state.backend;$('settingCash').value=state.startingCash;$('settingFee').value=(state.feeRate*100).toFixed(2);$('settingSlippage').value=(state.slippageRate*100).toFixed(2);
  document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===state.mode));
  bindUI();renderProviders();renderAll();log('SYSTEM','BRAVIA V3 initialized · real-money execution hard-locked');
  await discoverProducts();renderAll();connectMarket();refreshMemes();if(state.backend)connectBackendStream();
  setInterval(evaluateNormalBot,400);setInterval(evaluateMemePositions,650);setInterval(evaluateMemeNormalBot,800);setInterval(arenaTick,800);setInterval(()=>{if(!document.hidden)refreshMemes()},6500);setInterval(()=>{updateRiskStats();scheduleRender()},1200);
  if('serviceWorker'in navigator&&!DEMO)navigator.serviceWorker.register('./sw.js').catch(()=>{});
}

boot().catch(e=>{console.error(e);log('ERROR',`Boot error: ${e.message}`);toast('BRAVIA boot error — check console')});
