name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Compilar EXE
        run: npm run dist

      - name: Subir archivos compilados
        uses: actions/upload-artifact@v4
        with:
          name: WormGPT-Windows
          path: dist/**
